--Mostrar el DNI de aquellas personas que han sido atendidas por todos los sanitarios
--antes del 2020

SELECT P.DNI FROM PERSONA P WHERE NOT EXISTS (
    (SELECT S.DNI FROM SANITARIO)
    MINUS
    (SELECT V.DNI_S FROM VISITA WHERE P.DNI = V.DNI_P AND TO_DATE('01/03/2020', 'DD/MM/YYYY' ))
)

CREATE VIEW CONTACTO AS 

SELECT NOMBRE, APELLIDOS, DIRECCION, EMAIL FROM PERSONA NATURAL JOIN
(SELECT B.DNI1 FROM (PERSONA P JOIN CONTACTOS C AS P.DNI_P = C.DNI1) WHERE P.FDEF > SYSTEMDATE B GROUP BY B.DNI1 HAVING COUNT(*) > 50)


ALTER TABLE PERSONA ADD (GRUPO_DE_RIESGO CHAR(2) CHECK (GRUPO_DE_RIESGO = 'SI' OR GRUPO_DE_RIESGO = 'NO'));

UPDATE PERSONA SET GRUPO_DE_RIESGO = 'SI' WHERE (LO DE LA EDAD)