--Muestra la denominacion de los sitios donde hayan excavado todos 
--los equipos

SELECT DENOM FROM SITIO WHERE NOT EXISTS (
    (SELECT E.EQ# FROM EQUIPO E)
    MINUS
    (SELECT EX.EQ# FROM EXCAVA EX WHERE E.EQ# = EX.EQ# AND SITIO.SITIO# = EX.SITIO#
)


UPDATE EQUIPO E SET BONUS=BONUS+5 WHERE EQ# IN (
    SELECT EQ# FROM EXCAVA EX WHERE EX.EQ# = E.EQ# GROUP BY EQ# HAVING SUM(NHALLAS) > 30
)